### ISSUE TITLE
Support for other git repository hostings & support for usage as a tool

### ISSUE THREAD

**Issue by adnanh** [kravinskylev/email_finder#3]
Why not add support for any public git repository hostings (i.e. bitbucket, gitlab, etc...), not just those hosted on github?

Maybe add support to run this command inside of a git repository folder that you cloned locally to get the list of associated names and emails?

Cheers!

**Comment by levthedev** [comment]
Interesting idea, I'll get working on that now. I think the default functionality should remain the same, but I'll allow users to pass command line arguments for other hosting solutions.

**Comment by levthedev** [comment]
Fixed in 1b819c3
