### ISSUE TITLE
Doesn't get all names / email addresses.

### ISSUE THREAD

**Issue by MrJoy** [kravinskylev/email_finder#6]
At present you'll only get the names/addresses of the original authors of each commit.  You can make the tool more comprehensive in many situations by adding `%cn` / `%ce` to get the names/emails of the individuals who applied the commit.

The easiest option here would be:

```
git log --pretty=format:'%an %ae%n%cn %ce'
```

**Comment by levthedev** [comment]
Good idea! Fixed in #94f47ba
